[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [
  { access = "read", path = "./contracts/test" },
  { access = "read", path = "./test" },
  { access = "read", path = "./offchain" },
]

[rpc_endpoints]
gnosis = "${RPC_GNOSIS}"
